COLUMN_DESCRIPTIONS = {
    "Record_ID": "Unique identifier for each financial record.",
    "Accounting_Year": "Financial reporting year.",
    "Accounting_Quarter": "Financial reporting quarter (Q1-Q4).",
    "Accounting_Month": "Financial reporting month.",
    "Accounting_Period": "Accounting period in YYYY-MM format.",
    "Underwriting_Year": "Year in which the policy was underwritten.",
    "Accident_Year": "Year in which the insured event occurred.",
    "Booking_Date": "Date the transaction was booked into the system.",
    "Region": "Geographical reporting region.",
    "Market_Unit": "Business market unit such as ANZ, Japan, US, Canada, etc.",
    "Country": "Country associated with the transaction.",
    "Business_Segment": "Business segment (typically REPC).",
    "Main_Line_of_Business": "High-level line of business such as Property, Casualty or Specialty.",
    "Line_of_Business": "Detailed insurance line of business.",
    "Type_of_Business": "Treaty, Facultative or Direct Insurance.",
    "Cedent_ID": "Unique identifier of the cedent.",
    "Cedent_Name": "Insurance company transferring risk to the reinsurer.",
    "Broker": "Broker facilitating the insurance transaction.",
    "Client_Management_ID": "Unique identifier for the client management team.",
    "Client_Manager": "Relationship manager responsible for the client.",
    "UW_Portfolio": "Underwriting portfolio responsible for the business.",
    "Client_Executive": "Senior executive responsible for the client.",
    "IFRS_Classification": "Accounting classification under IFRS standards.",
    "PCSS_Type": "Trust or Non-Trust business classification.",
    "P_Zero_Flag": "Indicates whether the business is new or existing.",
    "Renewal_Category": "Business renewal category.",
    "Direction_of_Business": "Inward or Outward reinsurance business.",
    "Premium": "Gross premium amount.",
    "Claims": "Total insurance claims incurred.",
    "Commission": "Commission paid on the business.",
    "Expenses": "Operational expenses associated with the business.",
    "Technical_Result": "Underwriting profit or loss after Claims, Commission and Expenses.",
    "Net_Premium": "Premium after deductions.",
    "Loss_Ratio": "Claims divided by Premium.",
    "Expense_Ratio": "Expenses divided by Premium.",
    "Combined_Ratio": "Loss Ratio plus Expense Ratio."
}